### ISSUE TITLE
Baby Piglin not working...

### ISSUE THREAD

**Issue by Team-PLC** [xXKeyleXx/MyPet#1420]
# Bug report

* [**Checked**] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

_I can't create a baby piglin on create command /mypetadmin create %player_name% Piglin baby skilltree:Combat name:ChangeMyName_

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

1. I use deluxemenu and the command will be run on console

```
  'piglin':
    material: piglin_spawn_egg
    slot: 28
    display_name: '&fPiglin'
    left_click_commands:
    - '[sound] UI_BUTTON_CLICK'
    - '[close]'
    - '[console] mypetadmin create %player_name% Piglin baby skilltree:Combat name:ChangeMyName<delay=48>'
    - '[console] tm msg %player_name% &f\n&fPiglin pet successfully spawned!<delay=48>'
    - '[sound] ENTITY_PLAYER_LEVELUP<delay=48>'
```
2. assuming that the player clicked the item on the menu...

## Expected behavior

_then the player should have a baby piglin spawned instead of adult._

## Actual behaviour

_it spawned an adult piglin even if I run the command on OP player_
https://i.imgur.com/U3suTWR.png

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.
[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/5370942/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version: git-Paper-228 (MC: 1.16.3)**

**MyPet Build/Version:  MyPet-3.11-SNAPSHOT-B1574.jar**
