### ISSUE TITLE
worldgroups.yml does not work

### ISSUE THREAD

**Issue by Epicnicity2016** [xXKeyleXx/MyPet#676]
worldgroups.yml file is not working.
There is a creative world on my server, players can pick up equipment in the creative and put in the pet and return to survival and take the armor.
My file is not separating the pets in the worlds.
Also I wanted to know how to disable the pet's in certain worlds
My configuration:
Version 1.3.2 B#859
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```
Groups:
 default:
  - CCWorld_nether
  - CCWorld_the_end
  - CCSurvive
 nopets:
  - CCWorld
  - BlockHuntArena1
  - Minigames
  - SandBox
  - SpleefArena1
  - SpleggArena1
  - SpleggArena2
  - SpleggArena3
  - SpleggArena4
  - TNTRunArena1
  - Cidade
```
