### ISSUE TITLE
food add name and lore.

### ISSUE THREAD

**Issue by xyblues** [xXKeyleXx/MyPet#947]
Like this.
```
MyPet:
  Pets:
    Bat:
      HP: 20.0
      Speed: 0.3
      Food: 
        item:357
        name:&d&lpet food
        lore:&7Feed your pet.
      LeashFlags: LowHp
      CustomRespawnTimeFactor: 0
      CustomRespawnTimeFixed: 0
      LeashItem: 420
```
