### ISSUE TITLE
Pets being lost?

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#972]
Please provide the following info.

**Bukkit/Spigot/Bungee Build/Version:**
Spigot 1.11.2-R0.1-Snapshot
**MyPet Build/Version:**
MyPet.2.3.4-b#451
**Do you use the premium version? (this wont change anything for you)**
Yes
**What is the expected result?**
Pets to be saved/stored regularly and on shut-down
**What happens instead of that?**
Some players are losing pets randomly after restarts/reloads
**Error:**
No errors can be found anywhere.. I've checked console and MyPet.log

I'd question my database information, but pets that touch the NPC are fine. It's only pets that never get put into storage that ever wind up missing:
```
    MySQL:
      Database: DATABASENAME
      TablePrefix: mypet
      Host:  HOSTIP
      Password: PASSWORD
      User: USERNAME
      Port: 3306
      MaxConnections: 10
```

I'd question if I needed '' around certain values, but like I said it's only non-stored pets that ever get removed. For example my Donkey has been placed into storage and it's never vanished, whether it's in storage at a restart or actively with me it's never disappeared. If I create/tame a wolf for myself however, and restart the server (even after a /save-all) and everything shuts down fine, the wolf is gone later on.
