### ISSUE TITLE
McMMO ability still hurts owner pet

### ISSUE THREAD

**Issue by zerafox** [xXKeyleXx/MyPet#975]
**Bukkit/Spigot/Bungee Build/Version:**
1.11.2 Spigot

**MyPet Build/Version:**
2.3.5 DevBuild#458
**Do you use the premium version? (this wont change anything for you)**
Yes
**What is the expected result?**
I expect McMMO abilities to not strike a player's own pet
**What happens instead of that?**
Instead a player's Serrated Strikes killed their own pet during a fight.
**Error:**
No errors.
`  OwnerCanAttackPet: false`
```
  Hooks:
    Kingdoms: true
    WorldGuard: true
    Citizens: true
    mcMMO: true
```
`INFO mcMMO (1.5.07) hook activated.`
